-- docker/mysql/init/003_import_excel.sql

-- 1. Insertar TODAS las Marcas primero (usamos IGNORE para saltar repetidas)
INSERT IGNORE INTO marcas (nombre) VALUES
('CDR Computers'),
('Genius'),
('HP'),
('Dell'),
('Bangho'),
('LG'),
('Optiplex'),
('Epson'),
('CDR'),
('AOC'),
('Goofoo'),
('SFX'),
('Samsung'),
('Lenovo'),
('Ken Brown'),
('X Vision'),
('Nuevo');

-- 2. Insertar Ítems con Categorías asignadas
INSERT INTO items (
  nombre,
  codigo,
  marca_id,
  modelo,
  nro_serie,
  cantidad,
  estado,
  area_departamento,
  fecha_alta,
  ubicacion,
  descripcion,
  categoria_id -- ¡Campo agregado!
)
VALUES
    -- --- COMPUTADORAS ---
    ('CPU', 'CENS52-INF-PC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'Compaq', NULL, 3, 'operativo', 'Informática', '2025-12-04', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'Compaq', NULL, 1, 'operativo', 'Informática', '2025-12-05', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'Compaq', NULL, 1, 'operativo', 'Informática', '2025-12-06', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC2', (SELECT id FROM marcas WHERE nombre = 'Optiplex' LIMIT 1), '210L', NULL, 1, 'operativo', 'Informática', '2025-12-07', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC3', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, '109838', 3, 'operativo', 'Informática', '2025-12-08', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC3', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-12-09', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC4', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, '109841', 3, 'operativo', 'Informática', '2025-12-10', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC4', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-12-11', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC5', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, '109839', 3, 'operativo', 'Informática', '2025-12-12', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),
    ('CPU', 'CENS52-INF-PC5', (SELECT id FROM marcas WHERE nombre = 'Dell' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-12-13', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Computadoras' LIMIT 1)),

    -- --- MONITORES ---
    ('Monitor', 'CENS52-INF-MON1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'V196', NULL, 3, 'operativo', 'Informática', '2025-11-09', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'V196', NULL, 1, 'operativo', 'Informática', '2025-11-10', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'V196', NULL, 1, 'operativo', 'Informática', '2025-11-11', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON2', (SELECT id FROM marcas WHERE nombre = 'LG' LIMIT 1), 'E1942', NULL, 1, 'operativo', 'Informática', '2025-11-12', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON3', (SELECT id FROM marcas WHERE nombre = 'LG' LIMIT 1), 'E1942', NULL, 3, 'operativo', 'Informática', '2025-11-13', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON3', (SELECT id FROM marcas WHERE nombre = 'LG' LIMIT 1), 'E1942', NULL, 1, 'operativo', 'Informática', '2025-11-14', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON4', (SELECT id FROM marcas WHERE nombre = 'LG' LIMIT 1), 'Flatron L1750SQ', NULL, 1, 'operativo', 'Informática', '2025-11-15', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON5', (SELECT id FROM marcas WHERE nombre = 'Samsung' LIMIT 1), 'SyncMaster 731n', NULL, 1, 'operativo', 'Informática', '2025-11-16', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON6', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'V196', NULL, 3, 'operativo', 'Informática', '2025-11-17', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON6', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'V196', NULL, 1, 'operativo', 'Informática', '2025-11-18', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON7', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'P202', NULL, 1, 'operativo', 'Informática', '2025-11-19', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON8', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'L1740', NULL, 1, 'operativo', 'Informática', '2025-11-20', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON9', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), '2055', NULL, 3, 'operativo', 'Informática', '2025-11-21', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON9', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), '2055', NULL, 1, 'operativo', 'Informática', '2025-11-22', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON10', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'P201', NULL, 3, 'operativo', 'Informática', '2025-11-23', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON10', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'P201', NULL, 1, 'operativo', 'Informática', '2025-11-24', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON11', (SELECT id FROM marcas WHERE nombre = 'Samsung' LIMIT 1), 'SyncMaster 731n', NULL, 1, 'operativo', 'Informática', '2025-11-25', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON12', (SELECT id FROM marcas WHERE nombre = 'Samsung' LIMIT 1), 'SyncMaster 731n', NULL, 1, 'operativo', 'Informática', '2025-11-26', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON13', (SELECT id FROM marcas WHERE nombre = 'Samsung' LIMIT 1), 'SyncMaster 731n', NULL, 1, 'operativo', 'Informática', '2025-11-27', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),
    ('Monitor', 'CENS52-INF-MON14', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'P201', NULL, 1, 'operativo', 'Informática', '2025-11-28', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Monitores' LIMIT 1)),

    -- --- PERIFÉRICOS (Proyectores, Parlantes, Impresoras, Cables) ---
    ('Proyector', 'CENS52-INF-PRO1', (SELECT id FROM marcas WHERE nombre = 'Epson' LIMIT 1), 'Powerlite 95', 'LKSK378003L', 1, 'operativo', 'Informática', '2025-11-29', 'Laboratorio', 'Color: Blanco', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Parlantes', 'CENS52-INF-PAR1', (SELECT id FROM marcas WHERE nombre = 'Nuevo' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-11-30', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Parlantes', 'CENS52-INF-PAR2', (SELECT id FROM marcas WHERE nombre = 'Ken Brown' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-12-01', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Parlantes', 'CENS52-INF-PAR3', (SELECT id FROM marcas WHERE nombre = 'X Vision' LIMIT 1), 'HS-207', NULL, 1, 'operativo', 'Informática', '2025-12-02', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Parlantes', 'CENS52-INF-PAR4', (SELECT id FROM marcas WHERE nombre = 'Lenovo' LIMIT 1), 'F17ZB05466297', NULL, 1, 'operativo', 'Informática', '2025-12-03', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Impresora', 'CENS52-INF-IMP1', (SELECT id FROM marcas WHERE nombre = 'Samsung' LIMIT 1), 'ML-3710', 'Z2K5BKCBC00499R', 1, 'operativo', 'Informática', '2025-12-04', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Impresora', 'CENS52-INF-IMP2', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'LaserJet 1606dn', 'J101VFR', 1, 'operativo', 'Informática', '2025-12-05', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Impresora', 'CENS52-INF-IMP3', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'LaserJet 1606dn', 'J101KGX', 1, 'operativo', 'Informática', '2025-12-06', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Impresora', 'CENS52-INF-IMP4', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'LaserJet P1606dn', 'JWR4JH9V240262', 1, 'operativo', 'Informática', '2025-12-07', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Impresora', 'CENS52-INF-IMP5', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'LaserJet P2055d', 'CNGXJ4B008', 1, 'operativo', 'Informática', '2025-12-08', 'Laboratorio', 'Color: Gris', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Cable VGA', 'CENS52-INF-VGA1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), NULL, NULL, 12, 'operativo', 'Informática', '2025-12-09', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),

    -- --- PERIFÉRICOS (Mouses) ---
    ('Mouse', 'CENS52-INF-MOU1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23591351', 20, 'operativo', 'Informática', '2025-12-10', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23732571', 1, 'operativo', 'Informática', '2025-12-11', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23591440', 1, 'operativo', 'Informática', '2025-12-12', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23715887', 1, 'operativo', 'Informática', '2025-12-13', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23591403', 1, 'operativo', 'Informática', '2025-12-14', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU2', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23715929', 1, 'operativo', 'Informática', '2025-12-15', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU3', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23715908', 1, 'operativo', 'Informática', '2025-12-16', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU4', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23591376', 1, 'operativo', 'Informática', '2025-12-17', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU5', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-SBF96', 'LZE23715868', 1, 'operativo', 'Informática', '2025-12-18', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU6', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'VW098AA', '6CQ117154R', 1, 'operativo', 'Informática', '2025-12-19', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU7', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'G6R30AA', '6CM51504JL', 1, 'operativo', 'Informática', '2025-12-20', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU8', (SELECT id FROM marcas WHERE nombre = 'Genius' LIMIT 1), 'DX-120', 'X66132205575', 11, 'operativo', 'Informática', '2025-11-09', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU9', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'G3Q35AA', 'CNB6191K51', 1, 'operativo', 'Informática', '2025-11-10', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU10', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-UV96', 'LKA23558686', 1, 'operativo', 'Informática', '2025-11-11', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU11', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'MSUOAS2', 'HWW5A3P', 1, 'operativo', 'Informática', '2025-11-12', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU12', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-UV96', 'LKA23559044', 1, 'operativo', 'Informática', '2025-11-13', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU13', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-UV96', 'LKA23556709', 1, 'operativo', 'Informática', '2025-11-14', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU14', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-UV96', 'LKA23230705', 1, 'operativo', 'Informática', '2025-11-15', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU15', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'M-UV96', 'LKA23712492', 1, 'operativo', 'Informática', '2025-11-16', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU16', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'VW098AA', '6CQ117138H', 1, 'operativo', 'Informática', '2025-11-17', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU17', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'VW098AA', '6CQ117120K', 1, 'operativo', 'Informática', '2025-11-18', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU18', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'VW098AA', '6CQ117160M', 1, 'operativo', 'Informática', '2025-11-19', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU19', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'VW098AA', '6CQ1171742', 1, 'operativo', 'Informática', '2025-11-20', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Mouse', 'CENS52-INF-MOU20', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'H4K64AA', '6CJ5020GQZ', 1, 'operativo', 'Informática', '2025-11-21', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),

    -- --- PERIFÉRICOS (Teclados) ---
    ('Teclado', 'CENS52-INF-TEC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', 'C0508074939', 3, 'operativo', 'Informática', '2025-11-20', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', NULL, 1, 'operativo', 'Informática', '2025-11-21', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', NULL, 1, 'operativo', 'Informática', '2025-11-22', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC1', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', NULL, 1, 'operativo', 'Informática', '2025-11-23', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC2', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', 'C0508074105', 1, 'operativo', 'Informática', '2025-11-21', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC3', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', 'C0508077142', 1, 'operativo', 'Informática', '2025-11-22', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC4', (SELECT id FROM marcas WHERE nombre = 'HP' LIMIT 1), 'SK-1688', NULL, 1, 'operativo', 'Informática', '2025-11-23', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1)),
    ('Teclado', 'CENS52-INF-TEC5', (SELECT id FROM marcas WHERE nombre = 'Genius' LIMIT 1), NULL, NULL, 1, 'operativo', 'Informática', '2025-12-01', 'Laboratorio', 'Color: Negro', (SELECT id FROM categorias WHERE nombre = 'Periféricos' LIMIT 1));